- name: Ensure lab machines are up
  connection: local
  hosts: localhost
  vars_files:
   - vars/metacloud_vars.yml
  tasks: 
#  - name: Ensure lab machines are up
#    os_security_group:
#      cloud: cloudweek
#      name: lab
#      description: lab security group for workstations

  - name: Ensure lab machines are up
    os_server:
      state: present
      name: "{{ item }}"
      key_name: "{{ keypair }}"
      flavor: "{{ m1large }}"
      security_groups: "{{ security_group }}"
      userdata:  "{{ lookup('file', 'files/coreos-python.sh') }}"
      image: "{{ coreos_image }}"
      meta: 
        ansible: "lab-machines"  
    with_items: 
      - lab01
      - lab02
      - lab03
      - lab04
      - lab05
      - lab06
      - lab07
      - lab08
    register: result
       
  - name: Wait for the post install script to finish
    pause: minutes=2
    when: result|changed

#  - debug: var=result.results

#  - debug: var={{item.openstack.public_v4}}
#    with_items: result.results

  - name: Add lab machines to the inventory
    add_host: hostname={{item.openstack.public_v4}} groupname=lab-machines
    with_items: result.results

- name: Ensure Lab is setup
  gather_facts: true
  hosts: lab-machines
  roles: 
    - lab
